apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rogfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-archive-gateway_rogfk_no
      fintlabs.no/org-id: rogfk.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-archive-gateway_rogfk_no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "rogfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "rogfk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/rogfk-no"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/rogfk-no/actuator/prometheus"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/rogfk-no/api/intern/arkiv"
      - op: add
        path: "/spec/env/-"
        value:
          name: "novari.flyt.archive.gateway.client.fint-archive.base-url"
          value: "https://api.felleskomponent.no"
      - op: add
        path: "/spec/env/-"
        value:
          name: "novari.flyt.resource-server.security.api.internal.authorized-org-id-role-pairs-json"
          value: |
            {
              "rogfk.no":["USER"],
              "vigo.no":["DEVELOPER", "USER"],
              "novari.no":["DEVELOPER", "USER"]
            }
      - op: add
        path: "/spec/env/-"
        value:
          name: "novari.kafka.topic.org-id"
          value: "rogfk-no"
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-api-vault/items/fint-flyt-v1-slack-webhook"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/rogfk-no/actuator/health"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/rogfk-no/actuator/prometheus"
    target:
      kind: Application
      name: fint-flyt-archive-gateway

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-archive-fint-client_rogfk_no"
      - op: replace
        path: "/spec/orgId"
        value: "rogfk.no"
    target:
      kind: FintClient
      name: fint-flyt-archive-fint-client
